services:
  server:
    build: ./server
    ports:
      - "4000:4000"
    env_file:
      - ./server/.env
    environment:
      - CLIENT_ORIGIN=http://localhost:3000

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
